### PR TITLE
Merge Lunch food menu to master

### PR DESCRIPTION
**Pull request by Jakarin-Jojo**

### CODE REVIEW

**Comment by touchtool** [comment]
Menu add price format

**Comment by touchtool** [comment]
need to list in alphabetical order.

**Comment by Jakarin-Jojo** [comment]
Thank you

**Comment by jbrucker** [comment]
Lunch menu prices are left justified.  Use column header "-----------:|" to make them right justified
as in the other sections.

Are menu items sorted alphabetically?

**Pull request merged**
