### PR TITLE
Merge night food menu to master

### PR DESCRIPTION
**Pull request by boom210232**

### CODE REVIEW

**Comment by touchtool** [comment]
need to list in alphabetical order.

**Comment by Ditthapeem** [comment]
Delete TODO in REAME.md file

**Comment by jbrucker** [comment]
You committed your `.idea` directory to the repo.  Please remove it.

**Comment by jbrucker** [comment]
In Menu.md, I notice a few things maybe you should look at:
1) the items are not in alphabetical order
2) the prices are left justified.  Shouldn't they be right justified?  Change the "-------|" to "----------:" to right justify.
3) what number format for prices?  Prices are usually written "40" or "40.00" or "40." but not usually "40.0".

Should all parts of the menu should use the same format for prices?

**Comment by boom210232** [comment]
already fixed it! Everyone agree with this edited?

**Comment by touchtool** [comment]
I agreed

**Comment by Ditthapeem** [comment]
It's look good now,

**Comment by Jakarin-Jojo** [comment]
I agreed

**Pull request merged**
