### PR TITLE
Create pull request for beverages menu

### PR DESCRIPTION
**Pull request by touchtool**

### CODE REVIEW

**Comment by Ditthapeem** [comment]
It look good.

**Comment by touchtool** [comment]
Thank you

**Comment by boom210232** [comment]
OK but you must change currency from bath to baht

**Comment by Jakarin-Jojo** [comment]
It is great

**Review by jbrucker — CHANGES_REQUESTED** [review]
"Bath" should be spelled "Baht". 
Since it occurs on every price, should we write "Baht" in column header instead of each item?

Items are not listed in alphabetical order.  Please re-order them.

"Tea" - what kind of tea?  Ice tea, hot tea, green tea?

**Pull request merged**
